- .gitignore
- apps/admin/.env.development
- configs/vite/package.json
- configs/vite/src/index.ts
- configs/vite/src/plugins/https.ts
- configs/vite/src/plugins/index.ts
- configs/vite/src/utils/index.ts
- packages/types/src/global.ts
- pnpm-lock.yaml
> chore: dev serve add https and http2

- packages/request/src/Axios.ts
- packages/request/src/axiosTransform.ts
- packages/request/src/constants.ts
> chore: fix typos

- apps/admin/src/pages/sys/login/forget-password-form.vue
- apps/admin/src/pages/sys/login/login-form.vue
- apps/admin/src/pages/sys/login/mobile-form.vue
- apps/admin/src/pages/sys/login/register-form.vue
- packages/vbenComponents/src/divider/src/Divider.vue
> fix: 修复登录页表单样式

- packages/utils/src/persist.ts
> fix: 修正store类型校验缺失问题

- apps/admin/src/router/routes/index.ts
- apps/admin/vite.config.ts
- packages/router/src/routes/index.ts
- packages/utils/src/router.ts
> feat: add loadRoutesFromModules

- .gitignore
- apps/admin/mock/_mock-server.ts
- apps/admin/package.json
- configs/lint/package.json
- configs/lint/stylelint.js
- configs/vite/package.json
- packages/styles/src/variables.css
- packages/vbenComponents/index.ts
- packages/vbenComponents/package.json
- packages/vbenComponents/src/table/src/Table.vue
- packages/vbenComponents/src/table/src/hooks/useInterceptor.ts
- packages/vbenComponents/src/table/src/scss/dark.scss
- packages/vbenComponents/src/table/src/scss/light.scss
- packages/vbenComponents/src/table/src/type.ts
- pnpm-lock.yaml
feat: vxe-table 样式变量化 以及基础的夜间样式
修复一些包错误版本号冲突（用pnpm规则强行允许）
一些代码中类型的错误修复
> Feat：vxe table demonic 实现vxe-table的css变量 可即时切换主题

- packages/styles/src/variables.css
- packages/vbenComponents/package.json
- pnpm-lock.yaml
1. Update vxe source code that improve virtual scroll performance.
2. Update dark mode css vars.
###
- [x ] Pull request template structure not broken
- [x ] My code follows the style guidelines of this project
- [x ] Is the code format correct
- [x ] Is the git submission information standard?
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my …
> feat: update vxe-table-demonic version

- apps/admin/src/hooks/setting/useHeaderSetting.ts
- apps/admin/src/hooks/setting/useMenuSetting.ts
- apps/admin/src/hooks/setting/useMultipleTabSetting.ts
> refactor: transfer `admin/hooks` to `@vben/hooks`

- packages/hooks/src/config/useAppConfig.ts
- packages/hooks/src/setting/useHeaderSetting.ts
- packages/hooks/src/setting/useMenuSetting.ts
- packages/hooks/src/setting/useMultipleTabSetting.ts
- packages/hooks/src/setting/useRootSetting.ts
- packages/hooks/src/setting/useTransitionSetting.ts
- packages/hooks/src/web/useFullContent.ts
> fix: header not show

- apps/admin/src/init-application.ts
- apps/admin/src/setting/project.ts
- packages/constants/src/menuEnum.ts
- packages/grid-layouts/src/components/constant.ts
- packages/hooks/src/config/useAppConfig.ts
- packages/hooks/src/setting/useMenuSetting.ts
- packages/layouts/bridge.ts
- packages/layouts/src/components/header.vue
- packages/layouts/src/components/mixSideBar/Menu.vue
- packages/layouts/src/components/setting/components/Content.vue
- packages/layouts/src/components/setting/components/Features.vue
- packages/layouts/src/components/setting/components/FooterButtons.vue
- packages/layouts/src/components/setting/components/InputNumberItem.vue
- packages/layouts/src/components/setting/components/NavigationBarPicker.vue
- packages/layouts/src/components/setting/components/SelectItem.vue
- packages/layouts/src/components/setting/components/SettingButton.vue
- packages/layouts/src/components/setting/components/SettingDrawer.vue
- packages/layouts/src/components/setting/components/SwitchItem.vue
- packages/layouts/src/components/setting/components/ThemeColorPicker.vue
- packages/layouts/src/components/setting/components/Transitions.vue
- packages/layouts/src/components/setting/constant.ts
- packages/layouts/src/index.vue
- packages/types/src/config.ts
- packages/types/src/menu.ts
- packages/types/src/setting.ts
> WIP: fix: project setting fail

- packages/hooks/src/config/useAppConfig.ts
- packages/layouts/bridge.ts
> fix: title not shown when sidebar is not collapsed

- packages/hooks/src/config/useAppConfig.ts
- packages/layouts/src/components/setting/components/FooterButtons.vue
> refactor: setting operation via useAppConfig

- packages/layouts/src/components/footer.vue
- packages/locale/index.ts
- packages/stores/src/modules/siteGeneral.ts
> fix: footer i18n

- packages/hooks/src/config/useAppConfig.ts
> fix: switch layout mode does not reset the collapsed menu setting

- packages/layouts/src/components/setting/components/Features.vue
> fix: fixed expanded menu switch

- packages/layouts/src/components/setting/components/Features.vue
> fix: expanded menu width

- packages/vbenComponents/src/form/src/Form.vue
Fixes: https://github.com/vbenjs/vben3/issues/109
> fix: 修复DynamicTags控件导致页面卡死

- configs/vite/package.json
- package.json
> chore: adjusting the pnpm peerDependencyRules position. close #90

- README.md
> fix: test pr and fix the readme.md content error and style

- packages/components/package.json
- pnpm-lock.yaml
https://github.com/vbenjs/vben3/blob/34be664211fc948ae0ea9cf4b3a808c6ee2121fc/packages/components/src/countdown-input/index.vue#L3
但是package.json缺少 `@vben/types`的引用
> chore(components): vben/components 缺少vben/types的包引用

- packages/layouts/src/mix-sidebar.vue
- packages/styles/src/variables.css
> fix: mix-sidebar not on the topest

- apps/admin/mock/demo/table.ts
closes #208
由于mock.js的package.json里没有node-canvas依赖倒置的
https://github.com/nuysoft/Mock/blob/c4d7cba01900b5c5bb8e3d474c8f5d07810ab72e/src/mock/random/image.js#L242-L251
先将图片用[pravatar](https://pravatar.cc/images)上的图片替换。
> fix: the mockjs library make development environment crashed

- packages/hooks/src/config/useTabs.ts
- packages/layouts/bridge.ts
- packages/layouts/src/components/tabs/components/TabRedo.vue
> fix: TabRedo not working

- packages/layouts/src/components/header.vue
fix:https://github.com/vbenjs/vben3/issues/213#issuecomment-1780610511
> fix:“顶部菜单混合模式”受commit:d8e4016影响(#213)

- apps/admin/tsconfig.json
- configs/lint/package.json
- configs/tsconfig/package.json
- configs/vite/package.json
- configs/vite/test/plugins/testpkg/tsconfig.json
- configs/vite/tsconfig.json
- package.json
- packages/grid-layouts/tsconfig.json
- packages/hooks/tsconfig.json
- packages/layouts/tsconfig.json
- packages/locale/tsconfig.json
- packages/router/tsconfig.json
- packages/stores/tsconfig.json
- packages/types/tsconfig.json
- packages/utils/tsconfig.json
- packages/vbenComponents/tsconfig.json
- pnpm-lock.yaml
> chore: ensure consistent package names in configs directory

- apps/admin/init-components.ts
- packages/vbenComponents/src/pageHeader/src/PageHeader.vue
> feat: add vbenpageheader component

- .vscode/settings.json
- apps/admin/src/pages/demo/StrengthMeter.vue
- packages/components/index.ts
- packages/components/package.json
- packages/components/src/strength-meter/index.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/demo.ts
> feat: add strength-meter demo

- apps/admin/mock/menu.ts
- packages/router/src/menus/index.ts
> fix: 'hideMenu' not working

- .vscode/settings.json
- apps/admin/src/pages/demo/feat/ripple.vue
- packages/directives/index.ts
- packages/directives/package.json
- packages/directives/src/ripple/index.less
- packages/directives/src/ripple/index.ts
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
- pnpm-lock.yaml
add ripple demo #182 
添加水波纹示例：closes #182 
> feat: add ripple demo

- apps/admin/src/pages/demo/feat/click-out-side.vue
- packages/components/index.ts
- packages/components/package.json
- packages/components/src/click-outside/index.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
- pnpm-lock.yaml
add click outside demo #176 
添加clickoutside组件示例    closes #176 
> feat: click outside demo

- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/helper/route.ts
- packages/router/src/page/exception/index.vue
- packages/router/src/page/index.ts
- packages/router/src/routes/basic.ts
- packages/router/src/routes/modules/demo/pages.ts
- pnpm-lock.yaml
Add exception demo ( #192 )
添加新的异常页面Demo。 closes #192 
> feat: add exception demo

- apps/admin/init-components.ts
- apps/admin/src/pages/demo/page/result/fail.vue
- apps/admin/src/pages/demo/page/result/success.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/pages.ts
- packages/vbenComponents/src/steps/src/Step.vue
- packages/vbenComponents/src/steps/src/Steps.vue
feat: add result demo & closes #190 
新增结果页demo
> feat: add result demo

- .gitignore
- apps/admin/mock/demo/account.ts
- apps/admin/src/apis/sys/account.ts
- apps/admin/src/pages/demo/system/account/index.vue
- apps/admin/src/pages/demo/system/role/index.vue
- apps/admin/src/pages/demo/system/role/modules/roleAddDraw.vue
- apps/admin/src/pages/demo/system/role/modules/schemas.ts
- apps/admin/src/pages/demo/system/role/schemas.tsx
- apps/admin/tsconfig.json
- packages/router/src/routes/modules/system.ts
> ✨ [feat] add role manager example.

- packages/hooks/src/web/useTheme.ts
- packages/layouts/src/components/menu/index.vue
- packages/layouts/src/components/menu/mix-sub-menu.vue
- packages/layouts/src/components/setting/components/ThemeEditor.vue
- packages/layouts/src/components/setting/components/ThemeSwitch.vue
- packages/layouts/src/left-menu.vue
- packages/layouts/src/mix-sidebar.vue
- packages/layouts/src/top-menu-mixed.vue
- packages/locale/src/lang/en/layout.ts
- packages/locale/src/lang/zh-CN/layout.ts
- packages/stores/src/modules/themeStore.ts
> feat: 侧边栏深色设置

- packages/vbenComponents/src/form/src/Form.vue
- packages/vbenComponents/src/table/src/Table.vue
删除了table中的无用属性 titleClass 这个属性不仅没啥用 而且影响了暗黑模式对于背景色的变更
> 修复了 form 对于初始值的赋值 删除了table中的无用属性 titleClass 

- apps/admin/init-components.ts
- packages/vbenComponents/src/spin/src/Spin.vue
feat: 添加Spin组件 https://github.com/vbenjs/vben3/issues/156#issue-1957328451
> feat(vbenComponents): add Spin(Loading)

- apps/admin/package.json
- apps/admin/src/pages/demo/feat/print.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
- pnpm-lock.yaml
> feat(demo): add Print (#171)

- apps/admin/init-components.ts
- apps/admin/src/hooks/web/useWatermark.ts
- apps/admin/src/pages/demo/feat/watermark.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
- packages/vbenComponents/src/watermark/src/Watermark.vue
feat: 添加水印组件
feat: 添加自定义hooks useWatermark(支持防篡改)
feat: 添加水印demo页面
组件方式创建水印支持自定义样式，
函数方式创建水印支持防篡改，修改水印dom属性或删除会自动恢复水印
预览图
> feat(demo): add Watermark page(水印-demo #181)

- configs/vite/src/index.ts
> feat: 开启vite热更新

- apps/admin/src/pages/demo/system/menu/modules/menuAddDraw.vue
- apps/admin/src/pages/demo/system/password/index.vue
- apps/admin/src/pages/demo/system/password/schemas.tsx
- apps/admin/src/pages/demo/system/role/modules/roleAddDraw.vue
- packages/router/src/routes/modules/system.ts
- packages/vbenComponents/src/form/src/Form.vue
> ✨ [feat] add 'password' demo

- apps/admin/src/pages/demo/feat/copy.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
> feat(demo): add copy demo page(文本复制-demo #178)

- apps/admin/src/pages/demo/feat/web-socket.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
> ✏️ feat: 添加websocket示例 close #168 
注意：测试websocket需要连接地址 ws://localhost:3300/test （可以自行启动一个服务测试）
> feat: 添加websocket示例

- apps/admin/init-components.ts
- apps/admin/src/app.vue
- apps/admin/src/pages/demo/feat/msg.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
- packages/vbenComponents/index.ts
- packages/vbenComponents/src/dialog/src/DialogProvider.vue
- packages/vbenComponents/src/index.ts
> ✏️ feat: 添加消息提示示例    close #180 
> feat: 添加消息提示示例 

- apps/admin/.env.development
- apps/admin/.env.production
- apps/admin/mock/auth.ts
- apps/admin/src/apis/sys/user.ts
- apps/admin/src/init-application.ts
- apps/admin/src/layout/components/app/AppProvider.tsx
- apps/admin/src/pages/demo/feat/request-demo.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/request/index.ts
- packages/request/package.json
- packages/request/src/Axios.ts
- packages/request/src/axiosTransform.ts
- packages/request/src/index.ts
- packages/router/src/routes/modules/demo/feat.ts
- pnpm-lock.yaml
> ✏️ feat: 测试自动重试请求示例 close #169 
新增依赖： axios-retry 
close #310 
> feat: 测试自动重试请求示例

- packages/components/package.json
- packages/components/src/scrollbar/bar.ts
- packages/components/src/scrollbar/scrollbar.vue
- packages/components/src/scrollbar/types.ts
- packages/components/src/scrollbar/util.ts
- pnpm-lock.yaml
feat: 滚动条组件添加了scrollTo和scrollBottom方法
后续 滚动组件函数示例页面(已完成) 会用上，先单独提一个PR，不然一次提交太多文件 不好回滚 
> feat(vbenComponents): 更新Scrollbar滚动条组件，添加滚动指定位置事件

- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/3-bug-cn.md
- apps/admin/package.json
- apps/admin/src/config.ts
- apps/gf-vben/package.json
- apps/gf-vben/src/config.ts
- package.json
- packages/stores/src/modules/siteGeneral.ts
vue-vben-admin -> vben3
vue-vben-admin-next-doc -> vben3-doc
> fix: address url

- apps/admin/mock/demo/account.ts
- apps/admin/src/apis/demo/account.ts
- apps/admin/src/init-application.ts
- apps/admin/src/layout/feature/index.vue
- apps/admin/src/layout/index.vue
- apps/admin/src/pages/demo/feat/session-timeout.vue
- apps/admin/src/pages/sys/login/session-timeout-login.vue
- apps/admin/src/store/user.ts
- packages/constants/src/designSetting.ts
- packages/hooks/src/config/useAppConfig.ts
- packages/hooks/src/setting/useRootSetting.ts
- packages/layouts/src/components/setting/components/Features.vue
- packages/layouts/src/components/setting/constant.ts
- packages/locale/src/lang/en/layout.ts
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/layout.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/request/src/index.ts
- packages/router/src/routes/modules/demo/feat.ts
> feat: add session timeout login demo

- apps/admin/init-components.ts
[[[[### `General`
](chore: remove app/admin useless compontents)](chore: remove app/admin useless compontents)](chore: remove app/admin useless compontents)](chore: remove app/admin useless compontents)
> chore: remove app/admin useless compontents

- apps/admin/src/pages/demo/feat/context-menu.vue
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/feat.ts
> feat:  add context-menu demo

- apps/admin/src/pages/demo/page/desc/basic/data.tsx
- apps/admin/src/pages/demo/page/desc/basic/index.vue
- apps/admin/src/pages/demo/page/desc/high/data.tsx
- apps/admin/src/pages/demo/page/desc/high/index.vue
- packages/components/src/description/typing.ts
- packages/locale/src/lang/en/routes.ts
- packages/locale/src/lang/zh-CN/routes.ts
- packages/router/src/routes/modules/demo/pages.ts
> feat: add desc page demo

- apps/admin/package.json
- apps/gf-vben/package.json
- configs/css-preprocess/package.json
- configs/lint/package.json
- configs/vite/package.json
- package.json
- packages/components/package.json
- packages/constants/package.json
- packages/directives/package.json
- packages/grid-layouts/package.json
- packages/hooks/package.json
- packages/layouts/package.json
- packages/locale/package.json
- packages/request/package.json
- packages/router/package.json
- packages/stores/package.json
- packages/styles/package.json
- packages/types/package.json
- packages/utils/package.json
- scripts/package.json
> chore: scripts clean 指令缩写

- packages/vbenComponents/src/checkbox/src/CheckboxGroup.vue
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [ x] Is the code format correct
- [x ] Is the git submission information standard?
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the …
> fix: 修复checkboxGroup组件不能按value数组选中默认值的bug;

- packages/utils/index.ts
- packages/vbenComponents/src/form/src/Form.vue
fix: 1.修复form表单嵌套属性赋值无效的问题  2. 修复form组件属性响应式失效的问题 [#340 ](https://github.com/vbenjs/vben3/issues/340)
> fix: 1.修复form表单嵌套属性赋值无效的问题  2. 修复form组件属性响应式失效的问题

- packages/layouts/src/components/trigger/SiderDragBar.vue
> 修复左侧菜单栏拖拽失效

- packages/demo/src/Modal/index.vue
> feat: Dialog类型的Modal

- apps/admin/src/setting/project.ts
- apps/admin/tsconfig.json
- configs/tsconfig/base.json
- package.json
- packages/types/src/config.ts
- packages/utils/src/color.ts
- packages/utils/src/util.ts
- pnpm-lock.yaml
- [] I have added tests that prove my fix is effective or that my feature works
> 调整业务目录ts配置使其正常工作
